---
title: "Stepping outside the laplacian kernel"
params:
  n_nodes: 400
  n_locs: 625 #squared
  n_statistical_units: 200 #[200,400,800,"VAR"]
---

## Introduction
```{r}
library(fdaPDE)
library(femR)
```


## Parameters
- set the parameters to generate the data
```{r}
n_units <- params$n_statistical_units
n_nodes <- params$n_nodes
n_locs <- params$n_locs
n_replicas <- params$n_replicas

seed = 467897965 ## for reproducibility purposes
```

## Data
Utils
```{r}
source("../r-utils/mesh_utils.R")
```

### Mesh
The usual unit square is considered
```{r}
mesh.2D <- unit_square.mesh(n_nodes)

## use n = N for the setting locations = mesh nodes
## (in this case, \Psi is the identity matrix)
## use n != N for the general case. Set n > N.

locations.obs.2D <- unit_square.locs(n_locs)
Psi <- Psi.matrix(mesh.2D, locations.obs.2D)
```

### Eigenfunctions
Dummy mesh object
```{r}
library(femR)

#define a dummy pde to get the stiffness matrix
mesh <- Mesh(
  list(
    nodes = mesh.2D$nodes,
    elements = mesh.2D$triangles,
    boundary = mesh.2D$nodesmarkers
  )
)
Vh <- FunctionSpace(mesh, fe_order=1)
u <- Function(Vh)
```

The differential operator consider an anisotropic diffusion term
```{r}
anisothropic_diffusion_op <- function(alpha, gamma){
  R <- matrix(
    c(cos(alpha),-sin(alpha),
      sin(alpha),cos(alpha)),
    nrow=2, ncol=2
    )
  Sigma <- matrix(
    c(1/sqrt(gamma),0,
      0,sqrt(gamma)),
    nrow=2, ncol=2
    )
  #define K
  K <- R %*% Sigma %*% t(R)
  
  return(
    function(f){ 
      return(femR::div(K*femR::grad(f)))
      }
    )
}
```


Eigenfunctions as evd of the stiffness matrix
```{r}
pde <- list()
pde[["isotrophic"]] <- list()
pde[["anisotrophic"]] <- list()

pde[["isotrophic"]]$diff_params <- c(0,1)
pde[["anisotrophic"]]$diff_params <- c(1/3*pi,1.5)

f <- function(points) { return(0*points[,1])} #forcing term set to 0

for(diff in c("isotrophic","anisotrophic")){
  #operator
  L <- anisothropic_diffusion_op(
    pde[[diff]]$diff_params[1],
    pde[[diff]]$diff_params[2]
  )
  #L2 norm
  L2norm <- L2norm.factory(mesh.2D, L) #function to compute the norm
  #evd
  evd <- eigen(Pde(L(u),f)$stiff(), symmetric = T, only.values = F)
  
  #eigen functions
  f1_fem <- evd$vectors[,9]
  f2_fem <- evd$vectors[,10] #10
  f3_fem <- evd$vectors[,4]

  f1 <- as.matrix(Psi %*% f1_fem/L2norm(f1_fem))
  f2 <- as.matrix(Psi %*% f2_fem/L2norm(f2_fem))
  f3 <- as.matrix(Psi %*% f3_fem/L2norm(f3_fem))
  pde[[diff]]$true_PCs <- cbind(f1,f2,f3)
}
```


## Visualization
```{r}
source("../r-utils/plot_utils.R")

for(diff in c("isotrophic","anisotrophic")){
  
  print(plot_eigenfunction(pde[[diff]]$true_PCs[,1],locations.obs.2D,paste("PC1,",diff))) 
  print(plot_eigenfunction(pde[[diff]]$true_PCs[,2],locations.obs.2D,paste("PC2,",diff)))
  print(plot_eigenfunction(pde[[diff]]$true_PCs[,3],locations.obs.2D,paste("PC3,",diff)))
}
```

```{r}
library(gridExtra)
grid_PCs <- list()

for(i in 1:3){
  grid_PCs[[i]] <- arrangeGrob(
    plot_eigenfunction(pde[["isotrophic"]]$true_PCs[,i],locations.obs.2D, "isotropic"),
    plot_eigenfunction(pde[["anisotrophic"]]$true_PCs[,i],locations.obs.2D, "anisotropic"),
    ncol=2, nrow=1, top = paste("PC",i,sep="")
    )
  
  ggsave(paste("plots/",
               "PC",i,
               "-Mesh",params$n_nodes,
               "-Obs",params$n_statistical_units,
               "-Locs",params$n_locs,
             ".pdf", sep=""), 
       grid_PCs[[i]], width = 10, height = 5)
}
```

```{r}
grid_PCs[[i]]
```

## Data generation
```{r}
data_generator <- function(M,true_PCs, scores_sd, error_sd, obs_path=NULL, seed=7050){
  set.seed(seed)
  data <- list()
  data_range <- max(true_PCs) - min(true_PCs)
  # (1) scores & exact data matrix
  data$scores <- matrix(nrow=M, ncol=ncol(true_PCs))
  data$original_data <- matrix(0,nrow=M, ncol=nrow(true_PCs))
  for(i in 1:ncol(true_PCs)){
    data$scores[,i] <- rnorm(n = M, sd = scores_sd[i] * data_range)
    data$original_data <- data$original_data + data$scores[,i] %*% t(true_PCs[,i])
  }
  # (2) add noise to the data matrix
  error <- rnorm(n = M * nrow(true_PCs), sd = error_sd*data_range)
  noisy_data <- data$original_data + error
  
  # (3) centering
  data$center_noisy <- colMeans(noisy_data)
  data$center_noisy <- matrix(rep(data$center_noisy, nrow(noisy_data)),
                     nrow = nrow(noisy_data),
                     byrow = TRUE)
  
  data$noisy_centred_data <- noisy_data - data$center_noisy
  
  if(!is.null(obs_path)){
    write.csv(format(data$noisy_centred_data, digits = 16),
            paste(obs_path,"datamatrix_centred.csv",sep="/")
    )
  }
  return(data)
}
```

```{r}
data <- data_generator(100,
                       cbind(f1,f2,f3),
                       c(0.4,0.3,0.2), 0.1
                       )
```


```{r}
true_PCs <- cbind(f1,f2,f3) 
M <- 100

set.seed(seed)
data <- list()
data_range <- max(true_PCs) - min(true_PCs)
# (1) scores & exact data matrix
data$scores <- matrix(nrow=M, ncol=ncol(true_PCs))

scores_sd <- c(0.4,0.3,0.2)
error_sd <- 0.1


data$original_data <- matrix(0,nrow=M, ncol=nrow(true_PCs))
for(i in 1:ncol(true_PCs)){
  data$scores[,i] <- rnorm(n=M, mean = 0, sd = scores_sd[i] * data_range)
  data$scores[,i] <- data$scores[,i] - mean(data$scores[,i])
  data$original_data <- data$original_data + data$scores[,i] %*% t(true_PCs[,i])
}

# (2) add noise to the data matrix
error <- matrix(rnorm(n = M * nrow(true_PCs), sd = error_sd*data_range),nrow=M)
error <- error - matrix(rep(colMeans(error),M), byrow=T, nrow=M)

data$noisy_data <- data$original_data + error
```

```{r}

```

