---
title: "fpca calibration"
params:
  n_nodes: 100
  n_locs: 144 #squared
  n_statistical_units: 50 #[200,400,800,"VAR"]
  n_replicas: 1
---

## Introduction
```{r}
library(fdaPDE)
library(femR)

mesh_data_path <- "../data/mesh/unit_square"
obs_data_path <- "../data/models/fpca/2D_test"
results_path <- "results"

file.remove(list.files(path = mesh_data_path, full.names = TRUE))
file.remove(list.files(path = obs_data_path, full.names = TRUE))
file.remove(list.files(path = results_path, full.names = TRUE))
```


## Parameters
- `params.json` modifies the run parameters
```{r}
library(jsonlite)

json_data <- fromJSON("params.json")

json_data$RunParams$RSVDType <- unbox("monolithic")
json_data$RunParams$n_pc <- unbox(3)

json_data$calibration$grid_dim <- unbox(30)
json_data$calibration$strategy <- unbox("gcv")
json_data$calibration$left <- unbox(-16)
json_data$calibration$right <- unbox(0)
json_data$calibration$n_folds <- unbox(10)

write_json(json_data, 
           "params.json", 
           pretty = TRUE)
```

- set the parameters to generate the data
```{r}
n_units <- params$n_statistical_units
n_nodes <- params$n_nodes
n_locs <- params$n_locs
n_replicas <- params$n_replicas

seed = 467897965 ## for reproducibility purposes
```


## Data
Utils
```{r}
source("../r-utils/mesh_utils.R")
```


```{r}
##(1) Mesh generation
mesh.2D <- unit_square.mesh(n_nodes, mesh_data_path)
#define a dummy pde to get the stiffness matrix
mesh <- Mesh(
  list(
    nodes = mesh.2D$nodes,
    elements = mesh.2D$triangles,
    boundary = mesh.2D$nodesmarkers
  )
)
Vh <- FunctionSpace(mesh, fe_order=1)
u <- Function(Vh)

##(2) Eigenfunctions
## use n = N for the setting locations = mesh nodes
## (in this case, \Psi is the identity matrix)
## use n != N for the general case. Set n > N.

locations.obs.2D <- unit_square.locs(n_locs,obs_data_path)


## (2.1) at mesh nodes
## evaluate eigenfunctions on mesh nodes (this is equivalent to get the FEM basis
## expansion of the eigenfunctions ). change values of a and b to select eigenfunction
L <- anisothropic_diffusion_op(
    pi/3, #angle
    1.5 #intensity
    )
f <- function(points) { return(0*points[,1])} #forcing term set to 0 

#evd
evd <- eigen(Pde(L(u),f)$stiff(), symmetric = T, only.values = F)
  


PCs.indexes <- c(20,29,4,6,9,7,15,24,25,8,5,10,11,14,17,19,16,12,21,22)

PCs.fem <- matrix(nrow = nrow(evd$vectors), ncol=length(PCs.indexes))

for(i in 1:length(PCs.indexes)){
  PCs.fem[,i] <- evd$vectors[,PCs.indexes[i]]
}

## (2.2) at locations (normalized)
#L2 norm
L2norm <- L2norm.factory(mesh.2D, L) #function to compute the norm

Psi <- Psi.matrix(mesh.2D, locations.obs.2D)

true_PCs <- matrix(nrow = nrow(Psi), ncol=length(PCs.indexes))
for(i in 1:length(PCs.indexes)){
  true_PCs[,i] <- as.matrix(Psi %*% PCs.fem[,i]/L2norm(PCs.fem[,i]))
}


##(3) Data generation
#-> generated for each replica
```

Visually
```{r}
source("../r-utils/plot_utils.R")

for(i in 1:length(PCs.indexes)){
  print(plot_eigenfunction(true_PCs[,i],locations.obs.2D,paste("PC",i,sep = ""))) 
}
```


## Metrics
```{r}
library(dplyr)

keys <- c("rsvd","replica","n_pc")

error_metrics <- c("signal_reconstruction_error")

#time_metrics <- c("exe_time","svd_time","other_time")

test_results <- 
   data.frame(matrix(nrow=0,ncol=length(c(keys,error_metrics))))
names(test_results) <- c(keys, error_metrics)

test_results[] <- lapply(test_results, function(x) numeric())

test_results$rsvd <- character()
```

```{r}
source("../r-utils/error_metrics.R")
```

## Run
```{r}
max_npc <- 20

for(curr_npc in 1:max_npc){
  cat("n_pc: ", curr_npc, "\n")
  json_data$RunParams$n_pc <- unbox(curr_npc)
  scores_sd <- seq(from=0.8,to=0.6,length.out=curr_npc)
  for(ind_rep in 1:n_replicas){
    #data 
    data <- data_generator(n_units,
                         true_PCs = as.matrix(true_PCs[,1:curr_npc]),
                         scores_sd = scores_sd,
                         error_sd = 0.1,
                         obs_path = obs_data_path,
                         seed = seed + 4*ind_rep)
    
    for(rsvd_solver in c("monolithic","sequential")){
      cat("Solver: ", rsvd_solver, "\n")
      
      
        
      json_data$RunParams$RSVDType <- unbox(rsvd_solver)
      if(rsvd_solver=="monolithic"){
        json_data$calibration$strategy <- unbox("kcv")
      }else{
        json_data$calibration$strategy <- unbox("gcv")
      }
      write_json(json_data, "params.json", pretty = TRUE)
      #run the program
      system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-debug/experiments/seqVSmono/seqVSmono")
      
      #load results
      est.PCs <- 
        as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
      est.Scores <- 
        as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))
      
      #compute errors & times
      errors <- compute.errors.FPCA(data, 
                                    est.PCs = est.PCs,
                                    est.Scores = est.Scores
                                    )
      
      test_results <- test_results %>%
        add_row(rsvd=rsvd_solver, n_pc=curr_npc, replica=ind_rep)
      new_row <- test_results$rsvd==rsvd_solver & 
        test_results$n_pc==curr_npc & 
        test_results$replica==ind_rep
      test_results[new_row, error_metrics] <- 
        sqrt(mean((data$scores%*%t(data$pcs)-est.Scores%*%t(est.PCs))^2))
    }
  }
}
```

### Visualizations
```{r}
source("../r-utils/plot_utils.R")
```

```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 

col_palette <- hue_pal()(5)
color_map <- c(
  "monolithic" = col_palette[1],
  "sequential" = col_palette[2]
)

```




#### Errors
```{r}
save <- F

test_results$n_pc <- as.factor(test_results$n_pc)

for(err in error_metrics){
  plot <- 
    grouped_lineplot(test_results, 
                    "test",
                var_name.x = "n_pc", var_name.y = err,
                group_name = "rsvd", color_map = color_map,
                legend = T)
  print(plot)
  
  if(save){
    ggsave(paste("plots/",
               err,
               "-Mesh",params$n_nodes,
               "-Obs",params$n_statistical_units,
               "-Locs",params$n_locs,
             ".pdf", sep=""), 
         plot, width = 10, height = 5)
  }
}
```






