## Fit 
```{r}
#specify the params within the json file
library(jsonlite)
params_json <- fromJSON("params.json")

lambda_grid <- 10^seq(-8,-2,by=0.5)

params_json$RunParams$lambda_grid <- lambda_grid
write_json(path = "params.json", 
           params_json, auto_unbox=T, pretty=T, digits=10
)

#fit the model by running the program
system("./subspace_it")
```


## Results
```{r}
gcv_scores <- read.csv("test-results/gcv_scores.csv")
```

```{r}
# Sort lambda_grid (if not already sorted)
ord <- order(lambda_grid)
lambda_grid_sorted <- lambda_grid[ord]
gcv_scores_sorted <- gcv_scores[ord, ]

# Set up colors (one per curve)
num_curves <- ncol(gcv_scores_sorted)
curve_colors <- rainbow(num_curves)

# Plot GCV curves on log-log scale
matplot(lambda_grid_sorted, gcv_scores_sorted, type = "l", log = "xy",
        xlab = expression(lambda), ylab = "GCV Score",
        lty = 1, col = curve_colors, lwd = 2)

# Find minimum GCV scores and corresponding lambdas
min_indices <- apply(gcv_scores_sorted, 2, which.min)
min_lambdas <- lambda_grid_sorted[min_indices]
min_scores <- apply(gcv_scores_sorted, 2, min)

# Add points at minima
matpoints(min_lambdas, min_scores, pch = 21, bg = "white", col = curve_colors, cex = 1.5)


# Add a legend
legend("topleft", legend = paste("fPC", 1:num_curves, sep=""),
       col = curve_colors, lty = 1, lwd = 2, bty = "n", title = "GCV Curves")

```

