---
title: "Sparse monolithic"
params: 
  solver: "fspai_monolithic" #spchol_monolithic, simple_monolithic, fspai_monolithic
  n_nodes: 400
  n_locs: 625 #squared
  n_statistical_units: 200 #[200,400,800,"VAR"]
  n_cores: 1
---

## Introduction
```{r}
library(fdaPDE)
library(femR)

mesh_data_path <- "../data/mesh/unit_square"
obs_data_path <- "../data/models/fpca/2D_test"
results_path <- "results"

file.remove(list.files(path = mesh_data_path, full.names = TRUE))
file.remove(list.files(path = obs_data_path, full.names = TRUE))
```


## Parameters
- `params.json` modifies the run parameters
```{r}
library(jsonlite)

json_data <- fromJSON("params.json")

json_data$RunParams$RSVDType <- unbox(params$solver)
json_data$RunParams$n_cores <- unbox(params$n_cores)

json_data$RunParams$SVDType <- unbox("exact")
json_data$RunParams$lambda <- unbox(1e-2)

write_json(json_data, 
           "params.json", 
           pretty = TRUE)
```

- set the parameters to generate the data
```{r}
n_units <- params$n_statistical_units
n_nodes <- params$n_nodes
n_locs <- params$n_locs

seed = 467897965 ## for reproducibility purposes
```


## Data

Utils
```{r}
source("../include/mesh_utils.R")
source("../include/error_metrics.R")
```


```{r}
##(1) Mesh generation
mesh.2D <- unit_square.mesh(n_nodes, mesh_data_path)
L2norm <- L2norm.factory(mesh.2D) #function to compute the norm

##(2) Eigenfunctions
## use n = N for the setting locations = mesh nodes
## (in this case, \Psi is the identity matrix)
## use n != N for the general case. Set n > N.

locations.obs.2D <- unit_square.locs(n_locs,obs_data_path)

## (2.1) at mesh nodes
## evaluate eigenfunctions on mesh nodes (this is equivalent to get the FEM basis
## expansion of the eigenfunctions ). change values of a and b to select eigenfunction
f1_fem <- square_eigenfunction(a = 1, b = 1, mesh.2D$nodes)
f2_fem <- square_eigenfunction(a = 2, b = 3, mesh.2D$nodes)
f3_fem <- square_eigenfunction(a = 4, b = 4, mesh.2D$nodes)

## (2.2) at locations (normalized)
Psi <- Psi.matrix(mesh.2D, locations.obs.2D)

f1 <- as.matrix(Psi %*% f1_fem/L2norm(f1_fem))
f2 <- as.matrix(Psi %*% f2_fem/L2norm(f2_fem))
f3 <- as.matrix(Psi %*% f3_fem/L2norm(f3_fem))

true_PCs <- cbind(f1,f2,f3)

##(3) Data generation
data <- data_generator(n_units,
                       true_PCs = true_PCs,
                       scores_sd = c(0.4,0.3,0.2),
                       error_sd = 0.1,
                       obs_path = obs_data_path,
                       seed = seed)
```

## Run
```{r}
#run the program
system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/sparsity-monolithic/sparse_mono_fpca --gtest_filter=* --gtest_color=no")

#load results
est.PCs <- 
  as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
est.Scores <- 
  as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))

#compute errors & times
errors <- list()
errors$errPC <- vector()
errors$errScore <- vector()

for(ind_pc in 1:3){
  errors$RMSE.PCs[ind_pc] <- min(RMSE.vector(true_PCs[,ind_pc],est.PCs[,ind_pc]),
                            RMSE.vector(true_PCs[,ind_pc],-est.PCs[,ind_pc]))
  errors$Scores[ind_pc] <- min(RMSE.vector(data$scores[,ind_pc],est.Scores[,ind_pc]),
                          RMSE.vector(data$scores[,ind_pc],-est.Scores[,ind_pc]))
}
errors$signal_reconstruction <- RMSE.matrix(data$data_matrix,est.Scores%*%t(est.PCs))
errors$space_reconstruction <- subspace(true_PCs,est.PCs)

times <- list()
times$exe_time <- read.csv(file=paste(results_path,"execution_times.csv",sep="/"),
                           header=F)[[1]][1]
times$svd_time <- read.csv(file=paste(results_path,"time_svd.csv",sep="/"),
                           header=F)[[1]][1]
times$other_time <- read.csv(file=paste(results_path,"time_other.csv",sep="/"),
                             header=F)[[1]][1]
```

## Visualizations
```{r}
source("../include/plot_utils.R")
```


### Components
```{r}
plot_eigenfunction(est.PCs[,1],locations.obs.2D,"PC1")
plot_eigenfunction(est.PCs[,2],locations.obs.2D,"PC2")
plot_eigenfunction(est.PCs[,3],locations.obs.2D,"PC3")
```

### Sparsity patterns
```{r}
library(femR)

mesh <- Mesh(
    list(
      nodes = mesh.2D$nodes,
      elements = mesh.2D$triangles,
      boundary = mesh.2D$nodesmarkers
    )
  )
Vh <- FunctionSpace(mesh, fe_order=1)
u <- Function(Vh)
Lu <- -laplace(u) 
f <- function(points) { return(0*points[,1])}
pde <- Pde(Lu, f)

image(-pde$mass(), main = "Mass matrix")
image(pde$stiff(), main = "Stiffness matrix")
image(t(Psi)%*%Psi, main = "Psi^T*Psi")
```

