---
title: "fpca calibration"
params: 
  solver: "monolithic" #monolithic, sequential
  n_nodes: 400
  n_locs: 400 #squared
  n_statistical_units: 100 #[200,400,800,"VAR"]
  n_folds: 10
---

## Introduction
```{r}
mesh_data_path <- "../data/mesh/unit_square"
obs_data_path <- "../data/models/fpca/2D_test"
results_path <- "results"

plot_dir <- "plots/CV-curves"

file.remove(list.files(path = mesh_data_path, full.names = TRUE))
file.remove(list.files(path = obs_data_path, full.names = TRUE))
file.remove(list.files(path = results_path, full.names = TRUE))
```


## Parameters
- `params.json` modifies the run parameters
```{r}
library(jsonlite)

json_data <- fromJSON("params.json")

json_data$RunParams$RSVDType <- unbox(params$solver)
json_data$RunParams$n_pc <- unbox(3)

json_data$calibration$grid_dim <- unbox(50)
json_data$calibration$strategy <- unbox("gcv")
json_data$calibration$left <- unbox(-13)
json_data$calibration$right <- unbox(2)
json_data$calibration$n_folds <- unbox(params$n_folds)
json_data$calibration$fixed <- unbox(1e-5)
json_data$calibration$gcv_correction <- unbox(1)

write_json(json_data, 
           "params.json", 
           pretty = TRUE)
```

- set the parameters to generate the data
```{r}
n_units <- params$n_statistical_units
n_nodes <- params$n_nodes
n_locs <- params$n_locs

seed = 467897965 ## for reproducibility purposes
```


## Data
Utils
```{r}
source("../r-utils/mesh_utils.R")
```


```{r}
##(1) Mesh generation
mesh.2D <- unit_square.mesh(n_nodes, mesh_data_path)
mesh <- Mesh(
  list(
    nodes = mesh.2D$nodes,
    elements = mesh.2D$triangles,
    boundary = mesh.2D$nodesmarkers
  )
)
Vh <- FunctionSpace(mesh, fe_order=1)
u <- Function(Vh)

##(2) Eigenfunctions
## use n = N for the setting locations = mesh nodes
## (in this case, \Psi is the identity matrix)
## use n != N for the general case. Set n > N.

locations.obs.2D <- unit_square.locs(n_locs,obs_data_path)

## (2.1) at mesh nodes
## evaluate eigenfunctions on mesh nodes (this is equivalent to get the FEM basis
## expansion of the eigenfunctions ). change values of a and b to select eigenfunction
L <- anisothropic_diffusion_op(
    pi/3, #angle
    1.5#intensity
    )
f <- function(points) { return(0*points[,1])} #forcing term set to 0 

#evd
evd <- eigen(Pde(L(u),f)$stiff(), symmetric = T, only.values = F)
  
#eigen functions
f1_fem <- evd$vectors[,4]
f2_fem <- evd$vectors[,9]
f3_fem <- evd$vectors[,10]

## (2.2) at locations (normalized)
L2norm <- L2norm.factory(mesh.2D) #function to compute the norm
Psi <- Psi.matrix(mesh.2D, locations.obs.2D)

f1 <- as.matrix(Psi %*% f1_fem/L2norm(f1_fem))
f2 <- as.matrix(Psi %*% f2_fem/L2norm(f2_fem))
f3 <- as.matrix(Psi %*% f3_fem/L2norm(f3_fem))

true_PCs <- cbind(f1,f2,f3)

##(3) Data generation
data <- data_generator(n_units,
                       true_PCs = true_PCs,
                       scores_sd = c(0.4,0.3,0.2),
                       error_sd = 0.1,
                       obs_path = obs_data_path,
                       seed = seed)
```

Visually
```{r}
source("../r-utils/plot_utils.R")

print(plot_eigenfunction(true_PCs[,1],locations.obs.2D,paste("PC1,"))) 
print(plot_eigenfunction(true_PCs[,2],locations.obs.2D,paste("PC2,")))
print(plot_eigenfunction(true_PCs[,3],locations.obs.2D,paste("PC3,")))
```


```{r}
lambda_grid <- 10^seq(from=json_data$calibration$left,to=json_data$calibration$right,
                   length.out=json_data$calibration$grid_dim)
```


## True Errors
True reconstruction error
```{r}
source("../r-utils/error_metrics.R")

true_reconstruction_error <- function(rsvd_solver){
  rec_err <- numeric()
  proj_rec_err <- numeric()

  for(i in 1:length(lambda_grid)){
    json_data$RunParams$RSVDType <- unbox(rsvd_solver)
    json_data$calibration$strategy <- unbox("off")
    json_data$calibration$fixed <- unbox(lambda_grid[i])
    write_json(json_data, "params.json", pretty = TRUE, digits=10)
    
    #run the program
    system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/fpca-calibration/calibration_fpca")
    
    est.PCs <- as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
    est.Scores <- as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))
      
    #compute errors & times
    errors <- compute.errors.FPCA(data, 
                                  est.PCs = est.PCs,
                                  est.Scores = est.Scores
                                  )
    rec_err[i] <- errors$signal_reconstruction^2
    
    norm.Scores <- sweep(est.Scores, 2, STATS=sqrt(colSums(est.Scores^2)), FUN="/")
    projected_data <- norm.Scores%*%t(norm.Scores)%*%(data$scores%*%t(data$pcs))
    proj_rec_err[i] <- sqrt(mean((projected_data- est.Scores%*%t(est.PCs))^2))
  }
  
  plot <- ggplot(mapping=aes(x=lambda_grid,y=rec_err))+
          geom_line() +
          scale_x_log10() + 
          geom_point(mapping = aes(x=lambda_grid[which.min(rec_err)],y=min(rec_err)),
                     color="red", size=4) +
          ggtitle("signal reconstruction") 
  print(plot + scale_y_log10())
  print(lambda_grid[which.min(rec_err)])
  
  return(list(rec_err = rec_err, proj_rec_err = proj_rec_err))
}
```


## Run
```{r}
calibration_policies <- c("gcv","kcv")

CV_score <- list()
for(rsvd_solver in c("monolithic","sequential","subspace")){
  CV_score[[rsvd_solver]] <- data.frame(lambda=lambda_grid)
}


for(rsvd_solver in c("monolithic","sequential","subspace")){
  cat("Solver: ", rsvd_solver, "\n")

  for(cal_policy in c("full_smooth_gcv","kcv","gcv")){
    if(rsvd_solver=="sequential" && cal_policy=="full_smooth_gcv") next
    cat("Calibration policy: ", cal_policy, "\n")
    
    json_data$RunParams$RSVDType <- unbox(rsvd_solver)
    json_data$calibration$strategy <- unbox(cal_policy)
    write_json(json_data, "params.json", pretty = TRUE)
    #run the program
    system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/fpca-calibration/calibration_fpca")
    cv_values <- as.matrix(readMM(file=paste(results_path,"CV_values.mtx",sep="/")))
    
    CV_score[[rsvd_solver]][[cal_policy]] <- as.vector(cv_values)
    
    # 
    # 
    # if(cal_policy %in% c("gcv","full_smooth_gcv")){
    #   cv_values <- cv_values/params$n_statistical_units
    # }
    # 
    # 
    # plot <- ggplot(mapping=aes(x=lambda_grid))+
    #     geom_line(aes(y=cv_values),col="orange") +
    #     scale_x_log10() +
    #     geom_point(mapping = aes(x=lambda_grid[which.min(cv_values)],y=min(cv_values)),
    #                color="red", size=4) +
    #     geom_vline(xintercept = lambda_grid[which.min(rec_err)],
    #                linetype = "dashed", color = "darkgreen") +scale_y_log10()
    # 
    # if(cal_policy %in% c("gcv","kcv","kcv_cols")){
    #   plot <- plot + ggtitle(paste(rsvd_solver,"-",cal_policy))
    # }else{
    #   plot <- plot + ggtitle(paste(rsvd_solver,"- new_gcv"))
    # }
    # print(plot)
  }      
}
```

## CV-curves
```{r}
color_map <- c("GCV" = "red", 
                "K-Fold CV" = "darkgreen", 
                "Reconstruction" = "aquamarine3", 
                "Proj.Rec." = "violet")

save <- F
```


### Monolithic
True reconstruction error
```{r}
results <- true_reconstruction_error("monolithic")
rec_err_mono <- results$rec_err
proj_rec_err_mono <- results$proj_rec_err
```


CV-curves
```{r}
plot <- ggplot(data = CV_score[["monolithic"]], aes(x = lambda)) +
    geom_vline(xintercept = lambda_grid[which.min(rec_err_mono)],
                 color = "grey",
                 linetype = "dashed", linewidth=1) +
    geom_line(aes(y = full_smooth_gcv / sqrt(3 * params$n_statistical_units), 
                  color = "GCV"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(full_smooth_gcv)],
                             y=min(full_smooth_gcv / sqrt(3 * params$n_statistical_units)),
                             color="GCV"), size=3) +
    geom_line(aes(y = kcv, 
                  color = "K-Fold CV"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(kcv)],
                               y=min(kcv),
                               color="K-Fold CV"), size=3) +
    geom_line(aes(y = rec_err_mono, 
                  color = "Reconstruction"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(rec_err_mono)],
                                 y=min(rec_err_mono),
                                 color="Reconstruction"), size=3) +
    geom_line(aes(y = proj_rec_err_mono, 
                  color = "Proj.Rec."), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(proj_rec_err_mono)],
                                   y=min(proj_rec_err_mono),
                                   color="Proj.Rec."), size=3) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values = color_map) +
    theme_light() +
    ylab("CV-score") +
    theme(legend.position = "top",text = element_text(size=20)) +
    labs(color = NULL)  # Legend title

print(plot)

if(save){
  ggsave(paste(plot_dir,
              "/mono-CV-curves",
             ".pdf", sep=""), 
       plot, width = 10, height = 5)
}
```

### Sequential
True reconstruction error
```{r}
results <- true_reconstruction_error("sequential")
rec_err_seq <- results$rec_err
proj_rec_err_seq <- results$proj_rec_err
```

```{r}
plot <- ggplot(data = CV_score[["sequential"]], aes(x = lambda)) +
    geom_vline(xintercept = lambda_grid[which.min(rec_err_seq)],
                 color = "grey",
                 linetype = "dashed", linewidth=1) +
    geom_line(aes(y = gcv / sqrt(3 * params$n_statistical_units), 
                  color = "GCV"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(gcv)],
                             y=min(gcv / sqrt(3 * params$n_statistical_units)),
                             color="GCV"), size=3) +
    geom_line(aes(y = kcv, 
                  color = "K-Fold CV"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(kcv)],
                               y=min(kcv),
                               color="K-Fold CV"), size=3) +
    geom_line(aes(y = rec_err_seq, 
                  color = "Reconstruction"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(rec_err_seq)],
                                 y=min(rec_err_seq),
                                 color="Reconstruction"), size=3) +
    geom_line(aes(y = proj_rec_err_seq, 
                  color = "Proj.Rec."), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(proj_rec_err_seq)],
                                   y=min(proj_rec_err_seq),
                                   color="Proj.Rec."), size=3) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values = color_map) +
    theme_light() +
    ylab("CV-score") +
    theme(legend.position = "top",text = element_text(size=20)) +
    labs(color = NULL)  # Legend title

print(plot)

if(save){
  ggsave(paste(plot_dir,
              "/seq-CV-curves",
             ".pdf", sep=""), 
       plot, width = 10, height = 5)
}
```


### Subspace
True reconstruction error

```{r}
results <- true_reconstruction_error("subspace")
rec_err_sub <- results$rec_err
proj_rec_err_sub <- results$proj_rec_err
```

```{r}
plot <- ggplot(data = CV_score[["subspace"]], aes(x = lambda)) +
    geom_vline(xintercept = lambda_grid[which.min(rec_err_sub)],
                 color = "grey",
                 linetype = "dashed", linewidth=1) +
    geom_line(aes(y = gcv / sqrt(3 * params$n_statistical_units), 
                  color = "GCV"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(gcv)],
                             y=min(gcv / sqrt(3 * params$n_statistical_units)),
                             color="GCV"), size=3) +
    geom_line(aes(y = kcv, 
                  color = "K-Fold CV"), 
              linewidth = 1) +
    geom_point(mapping = aes(x=lambda_grid[which.min(kcv)],
                               y=min(kcv),
                               color="K-Fold CV"), size=3) +
    geom_line(aes(y = rec_err_sub, 
                  color = "Reconstruction"), 
              linewidth = 1, linetype="twodash") +
    geom_point(mapping = aes(x=lambda_grid[which.min(rec_err_sub)],
                                 y=min(rec_err_sub),
                                 color="Reconstruction"), size=3) +
    # geom_line(aes(y = proj_rec_err_sub, 
    #               color = "Proj.Rec."), 
    #           linewidth = 1) +
    # geom_point(mapping = aes(x=lambda_grid[which.min(proj_rec_err_sub)],
    #                                y=min(proj_rec_err_sub),
    #                                color="Proj.Rec."), size=3) +
    scale_x_log10() +
    scale_y_log10() +
    scale_color_manual(values = color_map) +
    theme_light() +
    ylab("CV-score") +
    theme(legend.position = "top",text = element_text(size=25)) +
    labs(x=expression(lambda), color = NULL)  # Legend title

print(plot)

if(save){
  ggsave(paste(plot_dir,
              "/sub-CV-curves",
             ".pdf", sep=""), 
       plot, width = 10, height = 5)
}
```

```{r}
ggsave(paste(plot_dir,
              "/sub-CV",
             ".pdf", sep=""), 
       plot, width = 10, height = 5)
```





