---
title: "A potential failure in the sequential fPCA"
params: 
  n_statistical_units: 400 #[200,400,800,"VAR"]
  lambda: 1
  n_replicas: 10 
---

## Introduction
```{r}
library(fdaPDE)
library(femR)

mesh_data_path <- "../data/mesh/unit_square"
obs_data_path <- "../data/models/fpca/2D_test"
results_path <- "results"

n_replicas <- params$n_replicas

file.remove(list.files(path = mesh_data_path, full.names = TRUE))
file.remove(list.files(path = obs_data_path, full.names = TRUE))
file.remove(list.files(path = results_path, full.names = TRUE))
```

Set the hyperparameters for the experiment by changing the file `params.json` in the folder 
```{r}
library(jsonlite)

json_data <- fromJSON("params.json")

json_data$RunParams$RSVDType <- unbox("sequential")
json_data$RunParams$fixed_lambda <- unbox(100)

json_data$SubspaceIterations$max_iter <- unbox(50)
json_data$SubspaceIterations$lambdas <- rep(100,3)


write_json(json_data, "params.json", pretty = TRUE)
```

- set the parameters to generate the data
```{r}
n_units <- params$n_statistical_units
n_replicas <- params$n_replicas

seed = 467897965 ## for reproducibility purposes
```

## Data
```{r}
source("../r-utils/mesh_utils.R")
generate.mesh_and_eigenfunctions <- function(n_nodes, mesh_path,
                                    n_locs, locs_path){
  ##(1) Mesh generation
  mesh.2D <- unit_square.mesh(n_nodes, mesh_path)
  #'define a dummy pde to get the stiffness and the mass matrices of the 
  #'differential operator
  mesh <- Mesh(
    list(
      nodes = mesh.2D$nodes,
      elements = mesh.2D$triangles,
      boundary = mesh.2D$nodesmarkers
    )
  )
  Vh <- FunctionSpace(mesh, fe_order=1)
  u <- Function(Vh)
  
  L <- anisothropic_diffusion_op(
    pi/3, #angle
    1.5 #intensity
    )
  f <- function(points) { return(0*points[,1])} #forcing term set to 0 
  pde <- Pde(L(u), f)
  
  ##(2) Eigenfunctions
  #evd
  evd <- eigen(Pde(L(u),f)$stiff(), symmetric = T, only.values = F)
  #at mesh nodes
  f1_fem <- evd$vectors[,4]
  f2_fem <- evd$vectors[,9]
  f3_fem <- evd$vectors[,10]

  ##(3) Evaluate at locations
  locations.obs.2D <- unit_square.locs(n_locs,locs_path) #locations at nodes
  Psi <- Psi.matrix(mesh.2D, locations.obs.2D)
  
  L2norm <- L2norm.factory(mesh.2D = mesh.2D, diff_op = L)
  
  #final components
  f1 <- as.matrix(Psi %*% f1_fem/L2norm(f1_fem))
  f2 <- as.matrix(Psi %*% f2_fem/L2norm(f2_fem))
  f3 <- as.matrix(Psi %*% f3_fem/L2norm(f3_fem))
  
  return(cbind(f1,f2,f3))
}
```


## Simple test
```{r}
k <- 40

true_PCs <- generate.mesh_and_eigenfunctions(
    k^2, mesh_data_path,
    k^2, obs_data_path
  )

data <- data_generator(n_units,
                   true_PCs = true_PCs,
                   scores_sd = c(0.4,0.3,0.2),
                   error_sd = 0.1,
                   obs_path = obs_data_path,
                   seed = seed)

locations <- expand.grid(seq(0,1,length.out=k), seq(0,1,length.out=k))
```

```{r}
source("../r-utils/error_metrics.R")
```


### Sequential 
```{r}
json_data$RunParams$RSVDType <- unbox("sequential")
json_data$RunParams$fixed_lambda <- unbox(1)
json_data$SubspaceIterations$lambdas <- rep(1,3)
write_json(json_data, "params.json", pretty = TRUE)
        
#run the program
system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/subspace_iterations/subspace_iterations")

#results
est.PCs <- as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
est.Scores <- as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))

source("../r-utils/plot_utils.R")

for(ind.PC in 1:3){
  plot <- plot_stat_units(est.PCs[,ind.PC],locations)
  print(plot)
  
  ggsave(paste(plot_dir,
               "/sequential/estPC",ind.PC,
             ".png", sep=""), 
       plot, width = 5, height = 5)
  plot <- plot_stat_units(data$pcs[,ind.PC],locations)
  print(plot)
  ggsave(paste(plot_dir,
               "/sequential/truePC",ind.PC,
             ".png", sep=""), 
       plot, width = 5, height = 5)
  
}

compute.errors.FPCA(data, 
                    est.PCs = est.PCs,
                    est.Scores = est.Scores
                    )

print(plot_stat_units((est.Scores%*%t(est.PCs))[1,],locations))
print(plot_stat_units((data$scores%*%t(data$pcs))[1,],locations))
print(plot_stat_units(data$noisy_data[1,],locations))


rowMeans((est.Scores%*%t(est.PCs)-data$scores%*%t(data$pcs))^2)
```

### Monolithic
```{r}
rsvd_solver <- "monolithic"

json_data$RunParams$RSVDType <- unbox(rsvd_solver)
json_data$RunParams$fixed_lambda <- unbox(1)
json_data$SubspaceIterations$lambdas <- rep(1,3)
write_json(json_data, "params.json", pretty = TRUE)
        
#run the program
system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/subspace_iterations/subspace_iterations")

#results
est.PCs <- as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
est.Scores <- as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))

source("../r-utils/plot_utils.R")

for(ind.PC in 1:3){
  plot <- plot_stat_units(est.PCs[,ind.PC],locations)
  print(plot)
  ggsave(paste(plot_dir,
               "/",rsvd_solver,"/estPC",ind.PC,
             ".png", sep=""), 
       plot, width = 5, height = 5)
  plot <- plot_stat_units(data$pcs[,ind.PC],locations)
  print(plot)
  ggsave(paste(plot_dir,
               "/",rsvd_solver,"/truePC",ind.PC,
             ".png", sep=""), 
       plot, width = 5, height = 5)
  
}

compute.errors.FPCA(data, 
                    est.PCs = est.PCs,
                    est.Scores = est.Scores
                    )

print(plot_stat_units((est.Scores%*%t(est.PCs))[1,],locations))
print(plot_stat_units((data$scores%*%t(data$pcs))[1,],locations))
print(plot_stat_units(data$noisy_data[1,],locations))
```

### Subspace
```{r}
rsvd_solver <- "subspace"

json_data$RunParams$RSVDType <- unbox(rsvd_solver)
json_data$RunParams$fixed_lambda <- unbox(1)
json_data$SubspaceIterations$lambdas <- rep(1,3)
write_json(json_data, "params.json", pretty = TRUE)
        
#run the program
system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/subspace_iterations/subspace_iterations")

#results
est.PCs <- as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
est.Scores <- as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))

source("../r-utils/plot_utils.R")

for(ind.PC in 1:3){
  plot <- plot_stat_units(est.PCs[,ind.PC],locations)
  print(plot)
  ggsave(paste(plot_dir,
               "/",rsvd_solver,"/estPC",ind.PC,
             ".pdf", sep=""), 
       plot, width = 5, height = 5)
  plot <- plot_stat_units(data$pcs[,ind.PC],locations)
  print(plot)
  ggsave(paste(plot_dir,
               "/",rsvd_solver,"/truePC",ind.PC,
             ".pdf", sep=""), 
       plot, width = 5, height = 5)
  
}

compute.errors.FPCA(data, 
                    est.PCs = est.PCs,
                    est.Scores = est.Scores
                    )

print(plot_stat_units((est.Scores%*%t(est.PCs))[1,],locations))
print(plot_stat_units((data$scores%*%t(data$pcs))[1,],locations))
print(plot_stat_units(data$noisy_data[1,],locations))
```

## Replicated tests
```{r}
library(dplyr)

keys <- c("rsvd","replica")

error_metrics <- c("errPC1","errPC2","errPC3",
                   "errScore1","errScore2","errScore3",
                   "signal_reconstruction_error",
                   "space_reconstruction_error")



time_metrics <- c("exe_time")

test_results <- 
   data.frame(matrix(nrow=0,ncol=length(c(keys,error_metrics,time_metrics, "scores_orth"))))
names(test_results) <- c(keys, error_metrics,time_metrics, "scores_orth")

test_results[] <- lapply(test_results, function(x) numeric())
test_results$rsvd <- character()
```


```{r}
for(i in 1:params$n_replicas){
  #->Generate the data
  data <- data_generator(n_units,
                   true_PCs = true_PCs,
                   scores_sd = c(0.4,0.3,0.2),
                   error_sd = 0.1,
                   obs_path = obs_data_path,
                   seed = seed + 4*i)
  
  for(rsvd_solver in c("monolithic","sequential","subspace")){
    json_data$RunParams$RSVDType <- unbox(rsvd_solver)
    json_data$RunParams$fixed_lambda <- unbox(1)
    json_data$SubspaceIterations$lambdas <- rep(1,3)
    write_json(json_data, "params.json", pretty = TRUE)
            
    #run the program
    system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/subspace_iterations/subspace_iterations")
    
    #results
    est.PCs <- as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
    est.Scores <- as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/")))
    
    errors <- compute.errors.FPCA(data, 
                      est.PCs = est.PCs,
                      est.Scores = est.Scores
                      )
    
    test_results <- test_results %>%
        add_row(rsvd=rsvd_solver, replica=i)
      new_row <- 
        test_results$rsvd==rsvd_solver & 
        test_results$replica==i
    test_results[new_row, error_metrics] <- unlist(errors)
    
    norm.Scores <- sweep(est.Scores, 2, STATS=sqrt(colSums(est.Scores^2)), FUN="/")
    test_results[new_row, "scores_orth"] <- sqrt(mean((eye(3)-t(norm.Scores)%*%norm.Scores)^2))
  }#rsvd_solver
}#replicas
```



## Visualization
```{r}
source("../r-utils/plot_utils.R")

color_map <- c(
  "sequential" = "#2297E6",
  "monolithic" = "#DF536B",
  "subspace" = "#F5C710"
)

plot_dir <- "plots-seq-failure"
```


### Legend
```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 
dummy_plot <- 
  ggplot(data.frame(x = 1:length(color_map), y=1:length(color_map),
                  method=names(color_map)), 
       aes(x = x, y = y, color = method)) +
  geom_point(size = 5) +  # Use points just for the purpose of displaying the legend
  scale_color_manual(values = color_map) +  # Use the custom color mapping
  theme_void() +                            # Remove axes and background
  labs(color = "Algorithm") +
  guides()



legend <- cowplot::get_legend(dummy_plot)
grid.newpage()
grid.draw(legend)

legend_grob <- grid.grabExpr(grid.draw(legend))

ggsave(paste(plot_dir,"/legend",
             ".pdf", sep=""), 
       legend_grob, width = 2, height = 2)
```


### Accuracy
#### PCs
```{r}
save <- F

for(i in 1:3){
  errPC.plot <- grouped_boxplot(subset(test_results,rsvd!="subspace"),
                 "rsvd", paste("errPC",i,sep=""),
                 group_name = "rsvd", color_map
                 ) 
  print(errPC.plot)
  
  if(save){
    ggsave(paste(plot_dir,
               "/errPC",i,
             ".pdf", sep=""), 
       errPC.plot, width = 10, height = 5)
  }
}
```

#### Scores
```{r}
for(i in 1:3){
  errScores.plot <- grouped_boxplot(subset(test_results,rsvd!="subspace"),
                 "rsvd", paste("errScore",i,sep=""),
                 group_name = "rsvd", color_map
                 ) 
  print(errScores.plot)
  
  if(save){
    ggsave(paste(plot_dir,
               "/errScore",i,
             ".pdf", sep=""), 
       errScores.plot, width = 10, height = 5)
  }
}
```

#### Signal
```{r}
errSignal.plot <- grouped_boxplot(test_results,
                 "rsvd", "signal_reconstruction_error",
                 group_name = "rsvd", color_map
                 ) 
print(errSignal.plot)

if(save){
  ggsave(paste(plot_dir,
              "/signal_rec",
             ".pdf", sep=""), 
       errSignal.plot, width = 10, height = 5)
}
```


```{r}
scores_orth.plot <- grouped_boxplot(subset(test_results,rsvd!="subspace"),
                 "rsvd", "scores_orth",
                 group_name = "rsvd", color_map
                 ) 
print(scores_orth.plot)

if(save){
  ggsave(paste(plot_dir,
              "/scores_orth",
             ".pdf", sep=""), 
       scores_orth.plot, width = 10, height = 5)
}
```


