Run the `data_generation.R` script before!
```{r}
loadings <- list()
model_names <- c("fpca-na-gcv","fsvt")

for(model_name in model_names){
  system(paste0("cd ", model_name, " && ", "./fit_model"),
         ignore.stdout = F)
  loadings[[model_name]] <- as.matrix(read.csv(paste0(model_name,"/test-results/loadings.csv")))
}

locs <- as.matrix(read.csv("data/fpca-na/locs.csv"))[,-1]
```

```{r}
library(fdaPDE)
library(femR)

## Unit square mesh ----
meshdir = "mesh/unit_square/"
options(warn=-1)
nodes = read.csv(paste0(meshdir, "points.csv"))[,2:3]
elements = read.csv(paste0(meshdir, "elements.csv"))[,2:4]
boundary = read.csv(paste0(meshdir, "boundary.csv"))[,2]
mesh.2D = create.mesh.2D(nodes = nodes, triangles = elements)

mesh <- Mesh(
  list(
    nodes = mesh.2D$nodes,
    elements = mesh.2D$triangles,
    boundary = mesh.2D$nodesmarkers
  )
)
```

```{r}
library(ggplot2)
library(scales)
library(magrittr)
library(dplyr)
library(viridis)

plot_stat_units <- function(stat_unit, locations, title=NULL, mybreaks=NULL, isolines=FALSE){
  ## data
  df <- data.frame(
    x = locations[,1],
    y = locations[,2],
    f = stat_unit
  )
  ## colors
  n_breaks <- 50
  if(is.null(mybreaks)){
    mybreaks <- c(-Inf, seq(min(df$f,na.rm=T), max(df$f,na.rm=T),
                            length.out = n_breaks), 
                  Inf)
  }
  mycolors <- colorRampPalette(viridis(11))(length(mybreaks) - 1)
  
  x_range <- range(locations[,1], na.rm = TRUE)
  y_range <- range(locations[,2], na.rm = TRUE)
  
  plot <- ggplot(df, aes(x = x, y = y, fill = f)) +
    geom_tile() +
    scale_fill_gradientn(
      colors = mycolors,
      breaks = mybreaks,
      name = "Value",
      na.value = "white"
    ) +
    coord_fixed(xlim = x_range, ylim = y_range, expand=F) +
    theme_void() +
    theme(legend.position = "none",
          #plot.title = element_text(hjust = 0.8),
          panel.border = element_rect(color = "black", fill = NA, size = 0.5),
          text = element_text(size=20))
  
  if(!is.null(title)){
    plot <- plot + ggtitle(title)
  }
  
  if(isolines){
    plot <- plot + geom_contour(data=df, aes(x = x, y = y, z = f), 
                                color = "black", breaks = mybreaks, size=0.2)
  }
  return(plot)
  
}
```

```{r}
for(idx in 1:3){
  for(model_name in model_names){
    print(plot_stat_units(loadings[[model_name]][,idx],mesh$nodes()))
  }
}
```
## GCV scores
```{r}
cv_scores_kcv <- as.matrix(read.csv("fpca-na-kcv/test-results/gcv_scores.csv"))
cv_scores_gcv <- as.matrix(read.csv("fpca-na-gcv/test-results/gcv_scores.csv"))


matplot(cbind(cv_scores_gcv,cv_scores_kcv),type="l", log="y")
points(which.min(cv_scores_kcv),min(cv_scores_kcv))
points(which.min(cv_scores_gcv),min(cv_scores_gcv))

```

## Errors
```{r}
Xn_fpca_gcv <- as.matrix(read.csv("fpca-na-gcv/test-results/reconstruction_at_locs.csv"))
Xn_fpca_fsvt <- as.matrix(read.csv("fsvt/test-results/reconstruction_locs.csv"))

mean((data$X_true-Xn_fpca_gcv)^2)
mean((data$X_true-Xn_fpca_fsvt)^2)
```


