---
title: "SVD comparison"
params: 
  n_units: 200
  n_nodes: 400
  n_locs: 625 #square
  n_cores: 1
  n_pc: 3
  lambda: 0.00001
  n_replicas: 10
---

## Introduction

- directories
```{r}
mesh_data_path <- "../data/mesh/unit_square"
obs_data_path <- "../data/models/fpca/2D_miss_test"
results_path <- "results"
plot_path <- "plots/"

file.remove(list.files(path = mesh_data_path, full.names = TRUE))
file.remove(list.files(path = obs_data_path, full.names = TRUE))
file.remove(list.files(path = results_path, full.names = TRUE))
```


## Parameters
- `params.json` 
```{r}
library(jsonlite)

json_data <- fromJSON("params.json")

json_data$RunParams$RSVDType <- unbox("monolithic")
json_data$RunParams$SVDType <- unbox("exact")
json_data$RunParams$lambda <- unbox(params$lambda)
json_data$RunParams$n_pc <- unbox(params$n_pc)
json_data$RunParams$start_recursion <- unbox(1)

write_json(json_data, "params.json", pretty = TRUE)
```

- data generation params
```{r}
seed = 467897965 ## for reproducibility purposes

n_nodes <- params$n_nodes #mesh nodes
n_locs <- params$n_locs #sampling at nodes
n_units <- params$n_units
```


## Test
```{r}
source("../r-utils/mesh_utils.R")
```

```{r}
ind.space.NA <- function(data_vector,p=0.5){
  size <- length(data_vector)
  data_vector[sample(1:size,size-round(size*p))] <- NA
  return(data_vector)
}
```


### Data generation
```{r}
##(1) Mesh generation
cat("\nNumber of Nodes: ", n_nodes,"\n")

mesh.2D <- unit_square.mesh(n_nodes,mesh_data_path)
mesh <- Mesh(
  list(
    nodes = mesh.2D$nodes,
    elements = mesh.2D$triangles,
    boundary = mesh.2D$nodesmarkers
  )
)
Vh <- FunctionSpace(mesh, fe_order=1)
u <- Function(Vh)

##(2) Eigenfunctions
## use n = N for the setting locations = mesh nodes
## (in this case, \Psi is the identity matrix)
## use n != N for the general case. Set n > N.

locations.obs.2D <- unit_square.locs(n_locs,obs_data_path)

## (2.1) at mesh nodes
## evaluate eigenfunctions on mesh nodes (this is equivalent to get the FEM basis
## expansion of the eigenfunctions ). change values of a and b to select eigenfunction
L <- anisothropic_diffusion_op(
    pi/3, #angle
    1.5 #intensity
    )
f <- function(points) { return(0*points[,1])} #forcing term set to 0 

#evd
evd <- eigen(Pde(L(u),f)$stiff(), symmetric = T, only.values = F)
  
#eigen functions
f1_fem <- evd$vectors[,20]
f2_fem <- evd$vectors[,29]
f3_fem <- evd$vectors[,4]

## (2.2) at locations (normalized)
L2norm <- L2norm.factory(mesh.2D, L) #function to compute the norm
Psi <- Psi.matrix(mesh.2D, locations.obs.2D)

f1 <- as.matrix(Psi %*% f1_fem/L2norm(f1_fem))
f2 <- as.matrix(Psi %*% f2_fem/L2norm(f2_fem))
f3 <- as.matrix(Psi %*% f3_fem/L2norm(f3_fem))

true_PCs <- cbind(f1,f2,f3)

##(3) Data generation + missing
#-> generated for each replica of the experiment
```

Visually
```{r}
source("../r-utils/plot_utils.R")

print(plot_eigenfunction(true_PCs[,1],locations.obs.2D,paste("PC1,"))) 
print(plot_eigenfunction(true_PCs[,2],locations.obs.2D,paste("PC2,")))
print(plot_eigenfunction(true_PCs[,3],locations.obs.2D,paste("PC3,")))
```

### Metrics
```{r}
library(dplyr)

keys <- c("rsvd","svd","replica")

error_metrics <- c("errPC1","errPC2","errPC3",
                   "errScore1","errScore2","errScore3",
                   "signal_reconstruction_error",
                   "space_reconstruction_error")

time_metrics <- c("exe_time")

test_results <- 
   data.frame(matrix(nrow=0,ncol=length(c(keys,error_metrics,time_metrics))))
names(test_results) <- c(keys, error_metrics,time_metrics)

test_results[] <- lapply(test_results, function(x) numeric())

test_results$rsvd <- character()
test_results$svd <- character()
```


Compute error metrics
```{r}
source("../r-utils/error_metrics.R")
```


### Run
```{r}
n_replicas <- 10
for(ind_rep in 1:n_replicas){
  #data
  data <- data_generator(n_units,
                       true_PCs = true_PCs,
                       scores_sd = c(0.4,0.3,0.2),
                       error_sd = 0.1,
                       seed = seed+4*ind_rep)
  #add missingness
  data$data_w_missing <- t(apply(data$noisy_data, 1, ind.space.NA))
  write.csv(format(data$data_w_missing, digits = 16),
          paste(obs_data_path,"datamatrix_centred.csv",sep="/"))
  
  
  for(rsvd_policy in c("monolithic","sequential")){
    for(svd_policy in c("exact","randomized")){
  
      json_data$RunParams$RSVDType <- unbox(rsvd_policy)
      json_data$RunParams$SVDType <- unbox(svd_policy)
      write_json(json_data, "params.json", pretty = TRUE)
      
      #run the program
      system("/Users/marcogalliani/Desktop/fdaPDE-cpp/cmake-build-default/experiments/missing-fpca/fpca_miss")
      
      #load results
      est.PCs <- 
        as.matrix(readMM(file=paste(results_path,"estimated_PCs.mtx",sep="/")))
      est.Scores <- 
        as.matrix(readMM(file=paste(results_path,"estimated_Scores.mtx",sep="/"))) 
      exe_time <- read.csv(file=paste(results_path,"execution_time.csv",sep="/"),
                           header = T)$V1
      
      #compute metrics
      errors <- compute.errors.FPCA(data,est.PCs,est.Scores)
      
      test_results <- test_results %>%
        add_row(rsvd = rsvd_policy, svd=svd_policy,replica = ind_rep)
      new_row <- test_results$rsvd==rsvd_policy & 
        test_results$svd==svd_policy & 
        test_results$replica==ind_rep
      
      test_results[new_row, error_metrics] <- 
        unlist(errors)
      test_results[new_row, time_metrics] <- exe_time
    }#miss policy
  }#rsvd policy
}#replica
```


```{r}
write.csv(test_results, 
          file = paste("past-runs",
                paste("svd-miss-comparison",
                      "-Mesh",params$n_nodes,
                      "-Obs",params$n_units,
                      "-Locs",params$n_locs,
                      ".csv",sep=""),
          sep="/"))
```



## Visualization
```{r}
test_results <- read.csv(
  file = paste("past-runs",
                paste("svd-miss-comparison",
                      "-Mesh",params$n_nodes,
                      "-Obs",params$n_units,
                      "-Locs",params$n_locs,
                      ".csv",sep=""),
          sep="/"),
  header = T
)
test_results$X <- NULL

names(test_results)[names(test_results)=="signal_reconstruction_error"] <- "rec_err"
```


```{r}
source("../r-utils/plot_utils.R")
```

```{r}
library(scales)
library(cowplot)
library(grid)
library(gridExtra) 

col_palette <- col_palette <- palette.colors(n=3, palette = "R4")
color_map <- c(
  "monolithic" = col_palette[2],
  "sequential" = col_palette[3]
)
```

### Errors
```{r}
save <- T

error_metrics <- c("errPC1","errPC2","errPC3",
                   "errScore1","errScore2","errScore3",
                   "rec_err",
                   "space_reconstruction_error")

for(err in c("errPC1","errPC2","errPC3",
             "errScore1","errScore2","errScore3")){
  
  plot <- grouped_boxplot(test_results,
                var_name.x = "svd", var_name.y = err,
                group_name = "rsvd", color_map = color_map,
                legend=F)
  
  print(plot)
  
  if(save){
    ggsave(paste("plots-SVD/",
               err,
               "-Mesh",params$n_nodes,
               "-Obs",params$n_obs,
               "-Locs",params$n_locs,
             ".pdf", sep=""), 
         plot, width = 10, height = 5)
  }
}


plot <- grouped_boxplot(test_results,
              var_name.x = "svd", var_name.y = "rec_err",
              group_name = "rsvd", color_map = color_map,
              legend=T)

print(plot)

if(save){
  ggsave(paste("plots-SVD/",
             "rec_err",
             "-Mesh",params$n_nodes,
             "-Obs",params$n_obs,
             "-Locs",params$n_locs,
           ".pdf", sep=""), 
       plot, width = 10, height = 5)
}


```

### Times
```{r}
save <- T

for(time in time_metrics){
  
  plot <- grouped_boxplot(test_results,
                var_name.x = "svd", var_name.y = time,
                group_name = "rsvd", color_map = color_map,
                legend=T) 
  
  print(plot)
  
  if(save){
    ggsave(paste("plots-SVD/",
               "exe_time",
               "-Mesh",params$n_nodes,
               "-Obs",params$n_obs,
               "-Locs",params$n_locs,
             ".pdf", sep=""), 
         plot, width = 10, height = 5)
  }
}
```

```{r}
med_times <- test_results %>% group_by(rsvd,svd) %>%
  summarise(exe_time = median(exe_time))

head(med_times)


library(dplyr)
library(tidyr)
med_times %>% pivot_wider(names_from = svd, values_from = exe_time) %>% 
  mutate(speed_up = exact/randomized) %>%
  select(rsvd, speed_up)
```
