
```{r}
loadings <- as.matrix(read.csv("/Users/marcogalliani/Projects/fdaPDE-cpp/experiments/data/fpca/loadings.csv"))
locs <- as.matrix(read.csv("/Users/marcogalliani/Projects/fdaPDE-cpp/experiments/data/fpca/locs.csv"))[,-1]
```

```{r}
library(fdaPDE)
library(femR)

## Unit square mesh ----
meshdir = "../data/mesh/unit_square/"
options(warn=-1)
nodes = read.csv(paste0(meshdir, "points.csv"))[,2:3]
elements = read.csv(paste0(meshdir, "elements.csv"))[,2:4]
boundary = read.csv(paste0(meshdir, "boundary.csv"))[,2]
mesh.2D = create.mesh.2D(nodes = nodes, triangles = elements)

mesh <- Mesh(
  list(
    nodes = mesh.2D$nodes,
    elements = mesh.2D$triangles,
    boundary = mesh.2D$nodesmarkers
  )
)

Psi <- Vh$basis()$eval(as.matrix(locs))
```


```{r}
library(ggplot2)
library(scales)
library(magrittr)
library(dplyr)
library(viridis)

plot_stat_units <- function(stat_unit, locations, title=NULL, mybreaks=NULL, isolines=FALSE){
  ## data
  df <- data.frame(
    x = locations[,1],
    y = locations[,2],
    f = stat_unit
  )
  ## colors
  n_breaks <- 50
  if(is.null(mybreaks)){
    mybreaks <- c(-Inf, seq(min(df$f,na.rm=T), max(df$f,na.rm=T),
                            length.out = n_breaks), 
                  Inf)
  }
  mycolors <- colorRampPalette(viridis(11))(length(mybreaks) - 1)
  
  x_range <- range(locations[,1], na.rm = TRUE)
  y_range <- range(locations[,2], na.rm = TRUE)
  
  plot <- ggplot(df, aes(x = x, y = y, fill = f)) +
    geom_tile() +
    scale_fill_gradientn(
      colors = mycolors,
      breaks = mybreaks,
      name = "Value",
      na.value = "white"
    ) +
    coord_fixed(xlim = x_range, ylim = y_range, expand=F) +
    theme_void() +
    theme(legend.position = "none",
          #plot.title = element_text(hjust = 0.8),
          panel.border = element_rect(color = "black", fill = NA, size = 0.5),
          text = element_text(size=20))
  
  if(!is.null(title)){
    plot <- plot + ggtitle(title)
  }
  
  if(isolines){
    plot <- plot + geom_contour(data=df, aes(x = x, y = y, z = f), 
                                color = "black", breaks = mybreaks, size=0.2)
  }
  return(plot)
  
}
```

```{r}
plot_stat_units(loadings[,1],mesh$nodes())
plot_stat_units(loadings[,2],mesh$nodes())
plot_stat_units(loadings[,3],mesh$nodes())

plot_stat_units(partial_data[6,],locations)
```

## Reconstruction error
```{r}
library(readr)
y_partial <- as.matrix(read_csv("/Users/marcogalliani/Projects/fdaPDE-cpp/experiments/data/fpca/y.csv"))[,-1]

y_rec_smoothed <- as.matrix(read.csv("/Users/marcogalliani/Projects/fdaPDE-cpp/experiments/data/fpca/y_reconstructed.csv"))

y_imputed <- y_partial
y_imputed[is.na(y_partial)] <- y_rec_smoothed[is.na(y_partial)]

y_original <- as.matrix(read.csv("/Users/marcogalliani/Projects/fdaPDE-cpp/experiments/data/fpca/y_complete.csv"))[,-1]

sqrt(mean((y_imputed-y_original)^2))
```

## DINEOF
```{r}
dineof_fit <- sinkr::dineof(y_partial)
sqrt(mean((dineof_fit$Xa-y_original)^2))
```


```{r}
sum(dineof_fit$Xa - y_partial,na.rm=T)
```

